language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo -H pip install pyinstaller

script:
  - ./build-with-pyinstaller.sh

after_success:
  - ./pyi-build/dist/jpylyzer --version
